import type { Metadata } from "next";
import { Inter, Barlow_Condensed, Rubik_Glitch } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const barlowCondensed = Barlow_Condensed({
    weight: ["700", "900"],
    variable: "--font-barlow-condensed",
    subsets: ["latin"],
});

const rubikGlitch = Rubik_Glitch({
    weight: "400",
    variable: "--font-rubik-glitch",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${inter.variable} ${barlowCondensed.variable} ${rubikGlitch.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <a href="#main" className="skip-link">
                    Skip to main content
                </a>
                <Nav />
                <main id="main">{children}</main>
            </body>
        </html>
    );
}
