// Generated by scripts/generate-posts-ts.ts — do not edit by hand.
import { meta as helloWorld } from "@/app/blog/hello-world/meta";
import { meta as settingUpPrettierWithTailwindCssInAReactProject } from "@/app/blog/setting-up-prettier-with-tailwind-css-in-a-react-project/meta";
import { meta as testingLmsApis } from "@/app/blog/testing-lms-apis/meta";
import { meta as testingPortfolioAccessibility } from "@/app/blog/testing-portfolio-accessibility/meta";
import { meta as testingTesting } from "@/app/blog/testing-testing/meta";
import { meta as webAccessibilityResourcesAndTools } from "@/app/blog/web-accessibility-resources-and-tools/meta";

/** Metadata for a single blog post. */
export interface PostMeta {
    title: string;
    description: string;
    date: string;
    readingTime: number;
    slug: string;
    thumbnail: { src: string; alt: string };
    topics: string[];
    draft: boolean;
}

/**
 * All posts sorted by date ascending (oldest first).
 *
 * Filter out drafts before rendering to users.
 */
export const POSTS: PostMeta[] = [
    helloWorld,
    settingUpPrettierWithTailwindCssInAReactProject,
    testingLmsApis,
    testingPortfolioAccessibility,
    testingTesting,
    webAccessibilityResourcesAndTools,
].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
