// scripts/generate-posts-ts.ts
import { promises as fs } from "fs";
import path from "path";

/**
 * Base paths for input discovery and output generation.
 */
const ROOT = process.cwd();
const BLOG_DIR = path.join(ROOT, "app", "blog");
const OUTPUT = path.join(ROOT, "lib", "posts.ts");

/**
 * Converts a kebab-case slug into a camelCase identifier.
 *
 * @param slug - Kebab-case string (for example, `"hello-world"`).
 * @returns camelCase identifier (for example, `"helloWorld"`).
 */
function toCamelCase(slug: string): string {
    return slug
        .split("-")
        .map((word, i) =>
            i === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1)
        )
        .join("");
}

/**
 * Returns the slug of every `app/blog/<slug>/meta.ts` that exists,
 * sorted alphabetically.
 *
 * @returns Sorted array of blog post slugs.
 */
async function findSlugs(): Promise<string[]> {
    const entries = await fs.readdir(BLOG_DIR, { withFileTypes: true });

    const results = await Promise.all(
        entries
            .filter((e) => e.isDirectory())
            .map(async (e) => {
                try {
                    await fs.access(path.join(BLOG_DIR, e.name, "meta.ts"));
                    return e.name;
                } catch {
                    return null;
                }
            })
    );

    return results.filter((s): s is string => s !== null).sort();
}

/**
 * Generates the content for `lib/posts.ts` from a list of slugs.
 *
 * @param slugs - Sorted array of blog post directory names.
 * @returns The full TypeScript source string.
 */
function generateSource(slugs: string[]): string {
    const imports = slugs
        .map(
            (slug) =>
                `import { meta as ${toCamelCase(slug)} } from "@/app/blog/${slug}/meta";`
        )
        .join("\n");

    const items = slugs.map((slug) => `    ${toCamelCase(slug)},`).join("\n");

    return `// Generated by scripts/generate-posts-ts.ts — do not edit by hand.
${imports}

/** Metadata for a single blog post. */
export interface PostMeta {
    title: string;
    description: string;
    date: string;
    readingTime: number;
    slug: string;
    thumbnail: { src: string; alt: string };
    topics: string[];
    draft: boolean;
}

/**
 * All posts sorted by date ascending (oldest first).
 *
 * Filter out drafts before rendering to users.
 */
export const POSTS: PostMeta[] = [
${items}
].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
`;
}

/**
 * Main entry point: scans the blog directory, generates `lib/posts.ts`,
 * and writes it to disk.
 *
 * @async
 * @returns Resolves when the file has been written.
 */
async function run() {
    const slugs = await findSlugs();
    const source = generateSource(slugs);
    await fs.writeFile(OUTPUT, source, "utf-8");
    console.log(`Wrote ${slugs.length} posts → lib/posts.ts`);
}

// Execute script.
run().catch((e) => {
    console.error(e);
    process.exit(1);
});
